### PR TITLE
Remove libboost

### PR DESCRIPTION
**Pull request by bobcheng15**
1. Remove libbost from the list of packages installed in the Dockerfile
2. Updated Lego so now it no longer depends on libboost

### CODE REVIEW

**Comment by bobcheng15** [comment]
@steveri, Gautham reworked the source code of Lego, so it no longer depends on libboost. Therefore, I have removed the installation of libboost from the Dockerfile. Hopefully this addresses the image size issue I introduced in my last PR merge.

**Comment by steveri** [comment]
Thanks guys!

But oops it looks like all three regression tests failed?
https://buildkite.com/stanford-aha/aha-flow/builds/10704

I will restart them to see if maybe it was a transient error...new attempt is in progress here:
https://buildkite.com/stanford-aha/aha-flow/builds/10705

**Comment by bobcheng15** [comment]
@steveri sounds good, thanks for catching the regression failure!

**Comment by steveri** [comment]
The other good news is (assuming we eventually get the CI to pass), it looks as though the docker image size is down to less than 6GB:
```
% docker images
REPOSITORY               TAG               IMAGE ID       CREATED             SIZE
stanfordaha/garnet       remove_libboost   4683f44eb0a1   About an hour ago   5.67GB
stanfordaha/garnet       latest            64581a7cbc7c   8 hours ago         6.98GB
stanfordaha/garnet       <none>            9bba7e64a05a   42 hours ago        8.14GB
stanfordaha/garnet       <none>            a8ccf33f2faf   2 days ago          8.14GB
stanfordaha/garnet       <none>            2365f0e0ebcf   6 weeks ago         7.41GB
```

**Comment by steveri** [comment]
All checks passed.
LGTM.
Thanks very much!

**Review by steveri — APPROVED** [review]

**Pull request merged**
