### PR TITLE
Add sparse dense conversion

### PR DESCRIPTION
**Pull request by bobcheng15**
1. Added mat_sp2dn and mat_dn2sp to the aha_submod and full regression. The matmul_ijk_crddrop_relu covers the primitive tested in mat_dn2sp, and mat_sp2dn is just mat_elemadd with one of the matrix being a dense empty matrix.
2. Point garnet and sam to the latest branch

### CODE REVIEW

**Review by kalhankoul96 — APPROVED** [review]
LGTM

**Comment by steveri** [comment]
@bobcheng15 I added and then removed some changes to your branch to debug some problems, see your email for details. I think I fixed the problem with the failing aha-flow test and restarted it for you, I think it will pass now. Sorry for the intrusion! -Steve

**Comment by bobcheng15** [comment]
@steveri  no worries, thanks for the work, I will take a look at the changes

**Comment by steveri** [comment]
> @steveri no worries, thanks for the work, I will take a look at the changes

Just to be clear: in the end, there were *no new changes* to this branch.

Instead I did a hotfix-change to the master branch(!) to make the regressions work...you can do e.g.
```
    git fetch origin
    git log -p origin/master
```
if you want to see the change there...

**Comment by bobcheng15** [comment]
> > @steveri no worries, thanks for the work, I will take a look at the changes
> 
> Just to be clear: in the end, there were _no new changes_ to this branch.
> 
> Instead I did a hotfix-change to the master branch(!) to make the regressions work...you can do e.g.
> 
> ```
>     git fetch origin
>     git log -p origin/master
> ```
> 
> if you want to see the change there...

got it, thanks for the help Steve!

**Pull request merged**
