### PR TITLE
Update Dockerfile - remove tmp install for torch

### PR DESCRIPTION
**Pull request by mbstrange2**
Remove the tmp dir for the torch install

### CODE REVIEW

**Comment by steveri** [comment]
Oops max I fixed the first problem but now it looks like we got a legitimate error related to our fix.

https://buildkite.com/stanford-aha/aha-flow/builds/9114#018abe93-8cad-4af8-bc0f-b25876b3c37d
```
Variable TMPDIR (/aha/tmp/torch_install/) is selecting a non-existent directory.
```

...I'm going to try setting TMPDIR="/tmp? and see if that fixes things...

**Comment by mbstrange2** [comment]
I’ll try storing it before changing it?
________________________________

**Comment by steveri** [comment]
> I’ll try storing it before changing it?

Actually yes, good point, I don't think setting to /tmp is the right thing after all. I'm going to try a different thing instead, i.e. instead of removing the whole directory, just remove the contents of the directory. Becasue the complaint mainly seems to be that it cannot find the directory itself, not the contents...

**Comment by mbstrange2** [comment]
Let's see what my change does then try that if not? I think this is safest in case anything else at all depends on the original value of `TMPDIR`. 👍

**Comment by steveri** [comment]
> Let's see what my change does then try that if not? I think this is safest in case anything else at all depends on the original value of `TMPDIR`. 👍

Oops I already did the other thing. But maybe that's okay, we can let them both run and see if one or both of them succeed...?

**Comment by mbstrange2** [comment]
> > Let's see what my change does then try that if not? I think this is safest in case anything else at all depends on the original value of `TMPDIR`. 👍
> 
> Oops I already did the other thing. But maybe that's okay, we can let them both run and see if one or both of them succeed...?

Sounds good

**Comment by steveri** [comment]
Okay, at first I didn't get what you were doing with TMPTMPDIR but now I understand. I like your way better than whatever I did.

Also it looks like yours worked and mine didn't :)

I will restore your fix and then we can finalize the pull.

**Comment by steveri** [comment]
@mbstrange2 Looks like everything is working now, thanks to your fix. Feel free to go ahead and merge whenever is convenient for you. (Ignore the failing "Docker Image CI" test, that's an on-going "no space left on device" problem that we are working on separately.)

**Review by steveri — APPROVED** [review]

**Comment by mbstrange2** [comment]
@steveri Thanks Steve :)

**Pull request merged**
