### PR TITLE
Aha smaller docker image2

### PR DESCRIPTION
**Pull request by steveri**
Speeds docker builds by doing cacheable layers first. Layers that are most likely to change, e.g. the one that copies the aha repo, go later in the `Dockerfile`. This reduces typical build time on our local machine from over an hour to less than 15 minutes.

Fixes "deprecated `tp_print`" warnings by installing Cython as `/usr/local/bin` instead of `/aha/bin`. No, I don't know why this works :(

Reduces docker image size by 1 GB by more aggressive cleanup after Halide build.

Introduces an image "ENTRYPOINT" script (`restore-halide-distrib.sh`) that restores a couple of the "cleaned-up" Halide files. The restoration only takes a couple of seconds. In return, the docker image is 400MB smaller than if the files were kept in place.

Cleans up a couple of comments and simplifies the code in a couple of places.

### CODE REVIEW

**Comment by kalhankoul96** [comment]
Looks good, you said its reduced to 15 minutes, but it says that "Docker Image CI / build (push) Succesful in 83m", what am I missing something?

**Comment by steveri** [comment]
> Looks good, you said its reduced to 15 minutes, but it says that "Docker Image CI / build (push) Succesful in 83m", what am I missing something?

This is probably worth a longer conversation. The full build still takes an hour. On machines where storage can persist across multiple builds, i.e. r7cad-docker (via buildkite instead of github actions), we can cache intermediate layers and reduce build time. Compare e.g. this initial build on r7cad-docker that took a little over an hour to build the image

https://buildkite.com/stanford-aha/aha-flow/builds/9229

vs. subsequent builds that took 13 minutes each, by using the cached information from build 9229:

https://buildkite.com/stanford-aha/aha-flow/builds/9236
https://buildkite.com/stanford-aha/aha-flow/builds/9237
https://buildkite.com/stanford-aha/aha-flow/builds/9238

Unfortunately, github actions build in the cloud using on-demand virtual machines, so no state is preserved between one build and the next. Github actions will always take the full hour to build :(

**Comment by kalhankoul96** [comment]
Got it, makes sense. Thanks Steve!

**Review by kalhankoul96 — APPROVED** [review]
LGTM

**Pull request merged**
