### PR TITLE
Fix verify script

### PR DESCRIPTION
**Pull request by steveri**
This merge does two things

1. Update my branch-verification script so that it always bases its test on the latest aha-flow master, rather than continuing to use stale versions after master changed;
2. Bump garnet to latest working version

### CODE REVIEW

**Comment by steveri** [comment]
I see that the weekly regression failed? I assume this something that has to be fixed before moving forward?
https://buildkite.com/stanford-aha/aha-flow/builds/8000

**Comment by steveri** [comment]
> Yeah, I think we should take a look at that first to be careful. But I don't think your pull request would conflict anyway.

So I took a quick look...it looks like the failure is related to this recent change in aha/util/regress.py:
```
git diff $good $bad -- aha/util/regress.py
-    buildkite_call(["aha", "map", test, "--env-parameters", env_parameters] + layer_array)
+    buildkite_call(["aha", "map", test, "--chain", "--env-parameters", env_parameters] + layer_array)
```

Without the "--chain", things seem to work okay I think, still looking at the remaining implications of that tho.

Are you and/or @jack-melchert currently looking at this as well and/or should I continue investigating?

**Comment by kalhankoul96** [comment]
Yeah @jack-melchert is looking into it, but he is at a conference today. I think if he can't figure it out soon (say by Thursday) we can just roll this back.

**Comment by steveri** [comment]
Passed full aha regression https://buildkite.com/stanford-aha/aha-flow/builds/8032
Merging now...

**Pull request merged**
