### PR TITLE
Parallel aha regressions cut runtime in half

### PR DESCRIPTION
**Pull request by steveri**
The main change here is that we have taken the 8-10 hour aha regression, that runs on every aha push, and split it into three parallel regressions, bringing the time down to about 4 hours instead.

> `Before: 7h 51m` <https://buildkite.com/stanford-aha/aha-flow/builds/10217>
> `After:  4h  1m` <https://buildkite.com/stanford-aha/aha-flow/builds/10220>

Also, I made some improvements in the way submod builds are reported. Somehow, the "Triggered From" links were incorrect, e.g. this build <https://buildkite.com/stanford-aha/aha-flow/builds/10222> says it was triggered from lake 5be0201, which does not exist. This more recent build, using the new changes, points to the correct lake change 0cca5c6:
<https://buildkite.com/stanford-aha/aha-flow/builds/10228>

The new code is quite ugly, but not significantly worse than what we had before. I hope to follow this pull quickly with a second pull whose only purpose will be to clean up the code, making it easier to maintain and understand.

-----
Here are the specific changes that you will see:

In `custom-checkout.sh`: removed a redundant git-branch checkout

In `update-pr-repo.sh`: fixed a bug in how builkite commit hash is derived (this is the "triggered-from" fix referred to above)

Disabled unused file `pr_trigger.yml`; it will be deleted entirely in the next go-round.

In `pipeline.yml`
- changed default regression config from "daily" to "aha_pr"
- added support for using aha dev branch instead of master, for development purposes
- simplified/shortened step labels by removing unnecessary emojis
- replaced single `aha_pr` step with three parallel steps `aha_pr1,2,3`

In `regress.py`
- replaced single `aha_pr` step with three parallel steps `aha_pr1,2,3`
- in the next go-round, I will restore the option for a single `aha_pr` step

### CODE REVIEW

**Review by yuchen-mei — APPROVED** [review]
The changes look good to me. Thanks!

**Review by kalhankoul96 — APPROVED** [review]
LGTM, I think what would clean it up the most is if we didn't have to have 3 separate lists aha1, aha2, aha3 in regress.py

**Review by Joejoedesu — APPROVED** [review]
Thank you so much for this work. LGTM

**Comment by steveri** [comment]
> LGTM, I think what would clean it up the most is if we didn't have to have 3 separate lists aha1, aha2, aha3 in regress.py

Yes that is top of list; the next go-round (hopefully very soon!) will greatly simplify the lists. Meanwhile, note that two of the three are just conv2 because that's the one that takes so long...

**Pull request merged**
