### PR TITLE
Add metamapper and peak_gen submodules

### PR DESCRIPTION
**Pull request by alexcarsello**
Adds new modules required by https://github.com/StanfordAHA/garnet/pull/834.

### CODE REVIEW

**Comment by steveri** [comment]
The checks have failed, and neither me nor Alex knows how to fix it...maybe one of the other reviewers has a clue?
@kalhankoul96 @Kuree @jack-melchert

**Comment by jack-melchert** [comment]
Yeah this happens when there is a dependency cycle anywhere in the submodules. Its likely that either peak_gen or metamapper has one of these cycles, I will try to find it now.

**Comment by jack-melchert** [comment]
Ok so the dependency cycle was between metamapper and lassen. This was fixed a couple of days ago in lassen master, but wasn't updated in this branch of aha flow yet. I've updated it to master so hopefully the checks pass now.

**Review by jack-melchert — APPROVED** [review]
Looks good! Thanks for figuring out how to make this branch work

**Review by Kuree — APPROVED** [review]

**Comment by steveri** [comment]
Thanks guys! I see that both the standard CI checks passed :)
Are there any other checks we need to do to make sure that everything really works now?

**Comment by Kuree** [comment]
I don't think so.

**Pull request merged**
