### PR TITLE
Aha smaller docker image

### PR DESCRIPTION
**Pull request by steveri**
These changes reduce docker image size from 11.5GB ish to about 8.5GB. The changes include:
- "make clean" after bison build: (30MB saving)
- remove smt-switch tests after successful smt-switch build (1.3GB)
- remove other smt-switch build deps after successful build (700M)
- remove intermediate builds of cvc5, bitwuzla, btor after successful install (100M)
- remove `coreir` intermediate build info after install (200M)
- "make clean" in clockwork after barvinok build (440M)
- remove soda codes after clockwork install (140M)

Here is a comparison of the new image size vs. that of the existing latest build
```
garnet              aha-flow-build-9199   e4fee95566ea    8.56GB
stanfordaha/garnet  latest                13276fc7711d    11.7GB
```

Also: I moved the top-level `aha` dir copy and `venv` setup so that it is the first thing in the Dockerfile, before setting up or installing submodules etc. It just seemed like a common-sense thing to do?

As a separate item, I added a line to the image's `.bashrc` file, to create a (empty) `/root/.modules` directory. Previously, whenever we loaded a container, we would get the annoying warning below (from `/cad/modules/tcl/ini/sh`). The existence of the empty `.modules` directory prevents the warning.
```
  % docker exec -ti $container /bin/bash
  +(0):WARN:0: Directory '/root/.modules' not found
  (aha) root@867c4aeb409c:/aha# 
```

### CODE REVIEW

**Comment by kalhankoul96** [comment]
Do you want to keep the before and after echos? It would probably trim down the file a bit to remove them and it might be easier to read. Otherwise, LGTM

**Review by kalhankoul96 — APPROVED** [review]
LGTM

**Comment by steveri** [comment]
> Do you want to keep the before and after echos? It would probably trim down the file a bit to remove them and it might be easier to read. Otherwise, LGTM

I'm going to keep them for now, for fear of mucking up a fragile build. I expect to do another cleanup turn very soon, taking off another one or two gigs of storage, and maybe cleaning up the format of the Dockerfile itself, including the before-and-after echos etc.

**Comment by kalhankoul96** [comment]
got it, sounds good!

**Pull request merged**
