### PR TITLE
update coreir

### PR DESCRIPTION
**Pull request by hofstee**

### CODE REVIEW

**Comment by hofstee** [comment]
@rdaly525 @leonardt do you know what's causing this to fail?

**Comment by leonardt** [comment]
hmm I see `ERROR: Dependency createfullinstancemap for removewires Was never loaded!` @rdaly525 did we make any changes to library loading recently? (CC @rsetaluri )

**Comment by leonardt** [comment]
Oh I know maybe, a typo in https://github.com/rdaly525/coreir/pull/911 with the dependency name

**Comment by leonardt** [comment]
Sorry this one with the full change: https://github.com/rdaly525/coreir/pull/913

**Comment by leonardt** [comment]
Should be fixed by https://github.com/rdaly525/coreir/pull/919, how do we update this PR once we merge the upstream coreir PR?

**Comment by hofstee** [comment]
I can take care of it, thanks for the quick fix!

**Comment by leonardt** [comment]
PR merged, let me know if there's still a problem

**Pull request merged**
