### PR TITLE
Unsharp fix

### PR DESCRIPTION
**Pull request by joyliu37**
1) Fix unsharp and rom mapping. 
2) Use the most recent clockwork branch.
3) Update garnet mini mapper for `mult_middle` operand

### CODE REVIEW

**Comment by joyliu37** [comment]
@Kuree Do you have any idea why the regression test pass but build fail?

**Comment by joyliu37** [comment]
Is this ok to merge?

**Comment by Kuree** [comment]
Why are so many files in garnet got updated?

**Comment by joyliu37** [comment]
This was check out from Taeyoung's glb-meta branch. But I think all my branch's change is included in Jeff's new PR, so we can just go with that one.

**Comment by joyliu37** [comment]
All my updates are include in this new PR https://github.com/StanfordAHA/aha/pull/1273. Closing this one.

**Comment by joyliu37** [comment]
The PR mention above is not make to master. I prune the garnet update to only the register pack and a mini mapper change.

**Review by Kuree — APPROVED** [review]

**Pull request merged**
