### PR TITLE
Test magma/coreir ndarray branches

### PR DESCRIPTION
**Pull request by leonardt**

### CODE REVIEW

**Comment by leonardt** [comment]
@hofstee this bumps the various repos to their requirements for the dependent merge, can I just bring this into master? It may be the case that the automatic bumping works because I don't know if there's explicit dependencies between the repos, but I tested them together since there were related feature additions

**Comment by leonardt** [comment]
It looks like this not being merged is causing problems for other tool builds, if I don't receive any feedback by today I'm going to go ahead and merge it to master to unblock others

**Comment by Kuree** [comment]
@leonardt Is it possible to use submodule in CoreIR? It seems like the problem is that CoreIR always pulls the latest verilogAST, even though there might be an API mismatch. Using submodule should fix the problem completely.

**Comment by leonardt** [comment]
Yea we can update it to do that

**Comment by leonardt** [comment]
https://github.com/rdaly525/coreir/pull/934

**Comment by leonardt** [comment]
Looks like these commits have been merged into master, closing

**Pull request closed without merging**
